name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite UTC

  workflow_dispatch: # Permite rodar manualmente no GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobra 🐍
        uses: Platane/snk@v3
        with:
          github_user_name: DUDUZIN8 # Substitua pelo seu usuário do GitHub
          outputs: |
            github-snake.svg
            github-snake-dark.svg?palette=github-dark

      - name: Enviar arquivos para o repositório
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
